name: oshigamimeguri
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.7
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.5
  uuid: ^3.0.7
  firebase_auth: ^4.7.3
  firebase_storage: ^11.2.6
  freezed_annotation: ^2.4.1
  algolia: ^1.1.2
  http: ^0.13.5
  geolocator: ^10.0.0
  geocoding: ^2.1.0

  google_maps_flutter: ^2.4.0

  go_router: ^10.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

dependency_overrides:
  intl: ^0.18.0-nullsafety.2
flutter:
  assets:
    - images/
  uses-material-design: true
