// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9TmuhRgqqQxoKkX6vLHDi45Br6vntQs',
    appId: '1:69763492633:web:759256e71249a5fca5f388',
    messagingSenderId: '69763492633',
    projectId: 'oshi-gami-meguri',
    authDomain: 'oshi-gami-meguri.firebaseapp.com',
    storageBucket: 'oshi-gami-meguri.appspot.com',
    measurementId: 'G-8PV4516H9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtMxyluMoGkBnUbobC6pMtrZyB4y_Itrw',
    appId: '1:69763492633:android:a854bbffb33e1bbfa5f388',
    messagingSenderId: '69763492633',
    projectId: 'oshi-gami-meguri',
    storageBucket: 'oshi-gami-meguri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzLgbntO_fuaLYT37MDdgFLdkOsopY6vY',
    appId: '1:69763492633:ios:b589382bf2b811f7a5f388',
    messagingSenderId: '69763492633',
    projectId: 'oshi-gami-meguri',
    storageBucket: 'oshi-gami-meguri.appspot.com',
    iosClientId: '69763492633-jn1vq9k2rtfgtuuurodnjsbpi2p1asgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.oshigamimeguri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzLgbntO_fuaLYT37MDdgFLdkOsopY6vY',
    appId: '1:69763492633:ios:93e55ac4a3e194d4a5f388',
    messagingSenderId: '69763492633',
    projectId: 'oshi-gami-meguri',
    storageBucket: 'oshi-gami-meguri.appspot.com',
    iosClientId: '69763492633-5hjnv058d82bmap0dqko41g9nu7g1qvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.oshigamimeguri.RunnerTests',
  );
}
